from layouts import all_non_specific_layouts, only_classic, remotely_modern
from skins.colors import generic_buttons, capcom_classic

capcom_usa_buttons = {
    "red": "#e2350a",
    "red_alt": "#e72a2e",
    "blue": "#3368cc",
    "blue_alt": "#1e7ea4",
}

sf_rando = {
    "red": "#e2350a",
    "green": "#1fc365",
    "blue": "#128ac7",
    "black": "#444444",
    "peach": "#fa9060",
    "yellow": "#f4d11f",
    "teal": "#02b4a6"
}

capcom = {
    "capcom_usa": {
        "button_a": capcom_usa_buttons["red"],
        "button_b": generic_buttons["white"],
        "button_x": capcom_usa_buttons["red"],
        "button_y": generic_buttons["white"],
        "l_bumper": None,
        "r_bumper": capcom_usa_buttons["blue"],
        "l_trigger": None,
        "r_trigger": capcom_usa_buttons["blue"],
        "variants": only_classic,
    },
    "capcom_usa_brw": {
        "button_a": capcom_usa_buttons["red"],
        "button_b": capcom_usa_buttons["blue"],
        "button_x": capcom_usa_buttons["red"],
        "button_y": capcom_usa_buttons["blue"],
        "l_bumper": None,
        "r_bumper": generic_buttons["white"],
        "l_trigger": None,
        "r_trigger": generic_buttons["white"],
        "variants": only_classic,
    },
    "capcom_usa_alt": {
        "button_a": capcom_usa_buttons["red_alt"],
        "button_b": generic_buttons["white"],
        "button_x": capcom_usa_buttons["red_alt"],
        "button_y": generic_buttons["white"],
        "l_bumper": None,
        "r_bumper": capcom_usa_buttons["blue_alt"],
        "l_trigger": None,
        "r_trigger": capcom_usa_buttons["blue_alt"],
        "variants": only_classic,
    },
    "capcom_usa_alt_brw": {
        "button_a": capcom_usa_buttons["red_alt"],
        "button_b": capcom_usa_buttons["blue_alt"],
        "button_x": capcom_usa_buttons["red_alt"],
        "button_y": capcom_usa_buttons["blue_alt"],
        "l_bumper": None,
        "r_bumper": generic_buttons["white"],
        "l_trigger": None,
        "r_trigger": generic_buttons["white"],
        "variants": only_classic,
    },
    "rando_cab": {
        "button_a": sf_rando["green"],
        "button_b": sf_rando["black"],
        "button_x": sf_rando["red"],
        "button_y": sf_rando["blue"],
        "l_bumper": None,
        "r_bumper": sf_rando["peach"],
        "l_trigger": None,
        "r_trigger": sf_rando["yellow"],
        "variants": only_classic,
    },
    "rando_cab_2": {
        "button_a": sf_rando["red"],
        "button_b": sf_rando["blue"],
        "button_x": sf_rando["yellow"],
        "button_y": sf_rando["teal"],
        "l_bumper": None,
        "r_bumper": generic_buttons["white"],
        "l_trigger": None,
        "r_trigger": sf_rando["green"],
        "variants": only_classic,
    },
    "classic_ryb": {
        "button_a": capcom_classic["red"],
        "button_b": capcom_classic["yellow"],
        "button_x": capcom_classic["red"],
        "button_y": capcom_classic["yellow"],
        "l_bumper": None,
        "r_bumper": capcom_classic["blue"],
        "l_trigger": None,
        "r_trigger": capcom_classic["blue"],
        "variants": only_classic,
    },
    "classic_rby": {
        "button_a": capcom_classic["red"],
        "button_b": capcom_classic["blue"],
        "button_x": capcom_classic["red"],
        "button_y": capcom_classic["blue"],
        "l_bumper": None,
        "r_bumper": capcom_classic["yellow"],
        "l_trigger": None,
        "r_trigger": capcom_classic["yellow"],
        "variants": only_classic,
    },
    "classic_byr": {
        "button_a": capcom_classic["blue"],
        "button_b": capcom_classic["yellow"],
        "button_x": capcom_classic["blue"],
        "button_y": capcom_classic["yellow"],
        "l_bumper": None,
        "r_bumper": capcom_classic["red"],
        "l_trigger": None,
        "r_trigger": capcom_classic["red"],
        "variants": only_classic,
    },
    "classic_bry": {
        "button_a": capcom_classic["blue"],
        "button_b": capcom_classic["red"],
        "button_x": capcom_classic["blue"],
        "button_y": capcom_classic["red"],
        "l_bumper": None,
        "r_bumper": capcom_classic["yellow"],
        "l_trigger": None,
        "r_trigger": capcom_classic["yellow"],
        "variants": only_classic,
    },
    "classic_ybr": {
        "button_a": capcom_classic["yellow"],
        "button_b": capcom_classic["blue"],
        "button_x": capcom_classic["yellow"],
        "button_y": capcom_classic["blue"],
        "l_bumper": None,
        "r_bumper": capcom_classic["red"],
        "l_trigger": None,
        "r_trigger": capcom_classic["red"],
        "variants": only_classic,
    },
    "classic_yrb": {
        "button_a": capcom_classic["yellow"],
        "button_b": capcom_classic["red"],
        "button_x": capcom_classic["yellow"],
        "button_y": capcom_classic["red"],
        "l_bumper": None,
        "r_bumper": capcom_classic["blue"],
        "l_trigger": None,
        "r_trigger": capcom_classic["blue"],
        "variants": only_classic,
    },
}
