from layouts import remotely_modern
from skins.colors import generic_buttons


buttons = {
    "punch": "#ed86a6",
    "kick": "#5188c4",
    "slash": "#ed86a6",
    "heavy_slash": "#e23e49",
    "dust": "#f47f20",
    "roman_cancel": "#e23f8e",
    "faultless_defense": "#7ef2a7",
    "taunt": "#dfd260",
    "dash": generic_buttons["gray"],
    "burst": "#7e2a28",
}

guilty_gear = {
    "type_a": {
        "button_a": buttons["punch"],
        "button_b": None,
        "button_x": buttons["kick"],
        "button_y": buttons["slash"],
        "l_bumper": None,
        "r_bumper": buttons['heavy_slash'],
        "l_trigger": None,
        "r_trigger": buttons["dust"],
        "variants": remotely_modern,
    },
    "type_a_6_button": {
        "button_a": buttons["punch"],
        "button_b": buttons["dash"],
        "button_x": buttons["kick"],
        "button_y": buttons["slash"],
        "l_bumper": None,
        "r_bumper": buttons['heavy_slash'],
        "l_trigger": None,
        "r_trigger": buttons["dust"],
        "variants": remotely_modern,
    },
    "type_a_8_button": {
        "button_a": buttons["punch"],
        "button_b": buttons["dash"],
        "button_x": buttons["kick"],
        "button_y": buttons["slash"],
        "l_bumper": generic_buttons["gray"],
        "r_bumper": buttons['heavy_slash'],
        "l_trigger": generic_buttons["gray"],
        "r_trigger": buttons["dust"],
        "variants": remotely_modern,
    },
    "type_a_8_button_macro": {
        "button_a": buttons["punch"],
        "button_b": buttons["dash"],
        "button_x": buttons["kick"],
        "button_y": buttons["slash"],
        "l_bumper": buttons["taunt"],
        "r_bumper": buttons['heavy_slash'],
        "l_trigger": buttons["roman_cancel"],
        "r_trigger": buttons["dust"],
        "variants": remotely_modern,
    },
    "type_b": {
        "button_a": buttons["heavy_slash"],
        "button_b": None,
        "button_x": buttons["punch"],
        "button_y": buttons["kick"],
        "l_bumper": None,
        "r_bumper": buttons['slash'],
        "l_trigger": None,
        "r_trigger": buttons["dust"],
        "variants": remotely_modern,
    },
    "type_b_6_button": {
        "button_a": buttons["heavy_slash"],
        "button_b": buttons["dash"],
        "button_x": buttons["punch"],
        "button_y": buttons["kick"],
        "l_bumper": None,
        "r_bumper": buttons['slash'],
        "l_trigger": None,
        "r_trigger": buttons["dust"],
        "variants": remotely_modern,
    },
    "type_b_8_button": {
        "button_a": buttons["heavy_slash"],
        "button_b": buttons["dash"],
        "button_x": buttons["punch"],
        "button_y": buttons["kick"],
        "l_bumper": generic_buttons["gray"],
        "r_bumper": buttons["slash"],
        "l_trigger": generic_buttons["gray"],
        "r_trigger": buttons["dust"],
        "variants": remotely_modern,
    },
    "type_b_8_button_macro": {
        "button_a": buttons["heavy_slash"],
        "button_b": buttons["dash"],
        "button_x": buttons["punch"],
        "button_y": buttons["kick"],
        "l_bumper": buttons["taunt"],
        "r_bumper": buttons["slash"],
        "l_trigger": buttons["roman_cancel"],
        "r_trigger": buttons["dust"],
        "variants": remotely_modern,
    },
    "type_c": {
        "button_a": buttons["dust"],
        "button_b": None,
        "button_x": buttons["punch"],
        "button_y": buttons["kick"],
        "l_bumper": None,
        "r_bumper": buttons['slash'],
        "l_trigger": None,
        "r_trigger": buttons["heavy_slash"],
        "variants": remotely_modern,
    },
    "type_c_6_button": {
        "button_a": buttons["dust"],
        "button_b": buttons["dash"],
        "button_x": buttons["punch"],
        "button_y": buttons["kick"],
        "l_bumper": None,
        "r_bumper": buttons['slash'],
        "l_trigger": None,
        "r_trigger": buttons["heavy_slash"],
        "variants": remotely_modern,
    },
    "type_c_8_button": {
        "button_a": buttons["dust"],
        "button_b": buttons["dash"],
        "button_x": buttons["punch"],
        "button_y": buttons["kick"],
        "l_bumper": generic_buttons["gray"],
        "r_bumper": buttons['slash'],
        "l_trigger": generic_buttons["gray"],
        "r_trigger": buttons["heavy_slash"],
        "variants": remotely_modern,
    },
    "type_c_8_button_macro": {
        "button_a": buttons["dust"],
        "button_b": buttons["dash"],
        "button_x": buttons["punch"],
        "button_y": buttons["kick"],
        "l_bumper": buttons["taunt"],
        "r_bumper": buttons["slash"],
        "l_trigger": buttons["roman_cancel"],
        "r_trigger": buttons["heavy_slash"],
        "variants": remotely_modern,
    },
    "type_d": {
        "button_a": buttons["kick"],
        "button_b": buttons["heavy_slash"],
        "button_x": buttons["punch"],
        "button_y": buttons["slash"],
        "l_bumper": None,
        "r_bumper": buttons['dust'],
        "l_trigger": None,
        "r_trigger": None,
        "variants": remotely_modern,
    },
    "type_d_6_button": {
        "button_a": buttons["kick"],
        "button_b": buttons["heavy_slash"],
        "button_x": buttons["punch"],
        "button_y": buttons["slash"],
        "l_bumper": None,
        "r_bumper": buttons['dust'],
        "l_trigger": None,
        "r_trigger": buttons["dash"],
        "variants": remotely_modern,
    },
    "type_d_8_button": {
        "button_a": buttons["kick"],
        "button_b": buttons["heavy_slash"],
        "button_x": buttons["punch"],
        "button_y": buttons["slash"],
        "l_bumper": generic_buttons["gray"],
        "r_bumper": buttons['dust'],
        "l_trigger": generic_buttons["gray"],
        "r_trigger": buttons["dash"],
        "variants": remotely_modern,
    },
    "type_d_8_button_macro": {
        "button_a": buttons["kick"],
        "button_b": buttons["heavy_slash"],
        "button_x": buttons["punch"],
        "button_y": buttons["slash"],
        "l_bumper": buttons["taunt"],
        "r_bumper": buttons['dust'],
        "l_trigger": buttons["roman_cancel"],
        "r_trigger": buttons["dash"],
        "variants": remotely_modern,
    },
    "type_e": {
        "button_a": buttons["slash"],
        "button_b": buttons["heavy_slash"],
        "button_x": buttons["punch"],
        "button_y": buttons["kick"],
        "l_bumper": None,
        "r_bumper": buttons['dust'],
        "l_trigger": None,
        "r_trigger": None,
        "variants": remotely_modern,
    },
    "type_e_6_button": {
        "button_a": buttons["slash"],
        "button_b": buttons["heavy_slash"],
        "button_x": buttons["punch"],
        "button_y": buttons["kick"],
        "l_bumper": None,
        "r_bumper": buttons['dust'],
        "l_trigger": None,
        "r_trigger": buttons["dash"],
        "variants": remotely_modern,
    },
    "type_e_8_button": {
        "button_a": buttons["slash"],
        "button_b": buttons["heavy_slash"],
        "button_x": buttons["punch"],
        "button_y": buttons["kick"],
        "l_bumper": generic_buttons["gray"],
        "r_bumper": buttons['dust'],
        "l_trigger": generic_buttons["gray"],
        "r_trigger": buttons["dash"],
        "variants": remotely_modern,
    },
    "type_e_8_button_macro": {
        "button_a": buttons["slash"],
        "button_b": buttons["heavy_slash"],
        "button_x": buttons["punch"],
        "button_y": buttons["kick"],
        "l_bumper": buttons["taunt"],
        "r_bumper": buttons['dust'],
        "l_trigger": buttons["roman_cancel"],
        "r_trigger": buttons["dash"],
        "variants": remotely_modern,
    },
}
