from layouts import remotely_modern
from skins.colors import generic_buttons

buttons = {
    "guard": "#01e26c",
    "punch": "#29d0f4",
    "kick": "#fb8cb6",
    "kick_red": "#d82b36",
}

virtua_fighter = {
    "classic_inverted": {
        "button_a": None,
        "button_b": buttons["kick"],
        "button_x": buttons["punch"],
        "button_y": buttons["guard"],
        "l_bumper": None,
        "r_bumper": None,
        "l_trigger": None,
        "r_trigger": None,
        "variants": remotely_modern,
    },
    "classic_inverted_4_button": {
        "button_a": generic_buttons["white"],
        "button_b": buttons["kick"],
        "button_x": buttons["punch"],
        "button_y": buttons["guard"],
        "l_bumper": None,
        "r_bumper": None,
        "l_trigger": None,
        "r_trigger": None,
        "variants": remotely_modern,
    },
    "classic_inverted_6_button": {
        "button_a": generic_buttons["white"],
        "button_b": buttons["kick"],
        "button_x": buttons["punch"],
        "button_y": buttons["guard"],
        "l_bumper": None,
        "r_bumper": generic_buttons["white"],
        "l_trigger": None,
        "r_trigger": generic_buttons["white"],
        "variants": remotely_modern,
    },
    "modern_inverted": {
        "button_a": None,
        "button_b": buttons["kick_red"],
        "button_x": buttons["punch"],
        "button_y": buttons["guard"],
        "l_bumper": None,
        "r_bumper": None,
        "l_trigger": None,
        "r_trigger": None,
        "variants": remotely_modern,
    },
    "modern_inverted_4_button": {
        "button_a": generic_buttons["white"],
        "button_b": buttons["kick_red"],
        "button_x": buttons["punch"],
        "button_y": buttons["guard"],
        "l_bumper": None,
        "r_bumper": None,
        "l_trigger": None,
        "r_trigger": None,
        "variants": remotely_modern,
    },
    "modern_inverted_6_button": {
        "button_a": generic_buttons["white"],
        "button_b": buttons["kick_red"],
        "button_x": buttons["punch"],
        "button_y": buttons["guard"],
        "l_bumper": None,
        "r_bumper": generic_buttons["white"],
        "l_trigger": None,
        "r_trigger": generic_buttons["white"],
        "variants": remotely_modern,
    },
    "classic_arcade": {
        "button_a": buttons["guard"],
        "button_b": None,
        "button_x": buttons["punch"],
        "button_y": buttons["kick"],
        "l_bumper": None,
        "r_bumper": None,
        "l_trigger": None,
        "r_trigger": None,
        "variants": remotely_modern,
    },
    "classic_arcade_4_button": {
        "button_a": buttons["guard"],
        "button_b": None,
        "button_x": buttons["punch"],
        "button_y": buttons["kick"],
        "l_bumper": None,
        "r_bumper": None,
        "l_trigger": None,
        "r_trigger": None,
        "variants": remotely_modern,
    },
    "classic_arcade_6_button": {
        "button_a": buttons["guard"],
        "button_b": None,
        "button_x": buttons["punch"],
        "button_y": buttons["kick"],
        "l_bumper": None,
        "r_bumper": generic_buttons["white"],
        "l_trigger": None,
        "r_trigger": generic_buttons["white"],
        "variants": remotely_modern,
    },
    "modern_arcade": {
        "button_a": buttons["guard"],
        "button_b": None,
        "button_x": buttons["punch"],
        "button_y": buttons["kick_red"],
        "l_bumper": None,
        "r_bumper": None,
        "l_trigger": None,
        "r_trigger": None,
        "variants": remotely_modern,
    },
    "modern_arcade_4_button": {
        "button_a": buttons["guard"],
        "button_b": generic_buttons["white"],
        "button_x": buttons["punch"],
        "button_y": buttons["kick_red"],
        "l_bumper": None,
        "r_bumper": None,
        "l_trigger": None,
        "r_trigger": None,
        "variants": remotely_modern,
    },
    "modern_arcade_6_button": {
        "button_a": buttons["guard"],
        "button_b": generic_buttons["white"],
        "button_x": buttons["punch"],
        "button_y": buttons["kick_red"],
        "l_bumper": None,
        "r_bumper": generic_buttons["white"],
        "l_trigger": None,
        "r_trigger": generic_buttons["white"],
        "variants": remotely_modern,
    },
}
